exclude = [
    "**/*__pycache__",
    "**/*egg-info",
    "**/docs",
    "**/tests",
    "**/venv",
]
source_roots = [
    ".",
]

[[modules]]
path = "lib.logging"
depends_on = []
utility = true

[[modules]]
path = "lib.feature_flag"
depends_on = []

[[modules]]
path = "lib.db"
depends_on = []

[[interfaces]]
from = ["lib.db"]
expose = ["connection"]

[[modules]]
path = "providers"
depends_on = ["lib.db"]

[[interfaces]]
from = ["providers"]
expose = ["get_providers", "get_provider"]

[[modules]]
path = "server"
depends_on = ["providers"]

[[modules]]
path = "apps.*"
depends_on = []

[[modules]]
path = "apps.*.service"
depends_on = ["apps.*.service"]

[[interfaces]]
from = ["apps.providers.service"]
expose = ["get_providers"]

[[interfaces]]
from = ["apps.licenses.service"]
expose = ["get_licenses"]
